### PR TITLE
006 -  compiler in new module

### PR DESCRIPTION
**Pull request by poz1**
Moved edu.mit.csail.sdg.
- alloy4
- ast
- parser
- sim 
- translator

to a new module ( org.alloytools.alloy.core ).

org.alloytools.alloy.application now depends on it

### CODE REVIEW

**Comment by pkriens** [comment]
Alessandro, can you give a quick intro of yourself? 

This is a big PR so I need a bit of time to verify everything. It is aligned with one of the changes I wanted to make but this also means I am probably going to be a bit more picky then a small commit :-) This kind of work is however, highly appreciated.

You also have to sign-off all your commits, see https://github.com/AlloyTools/org.alloytools.alloy/blob/master/CONTRIBUTING.md which implies you contribute under Apache ASL 2.0

Last but not least, I made a change that conflicts with your work. Please rebase.

We highly appreciate this work but I hope you understand we need to do this carefully.

**Comment by aleksandarmilicevic** [comment]
I'm fine with this change, but please follow the instruction Peter pointed out (namely, squash your commits into one and sign it off).

**Comment by pkriens** [comment]
Alessandro?

**Comment by poz1** [comment]
Hi @pkriens and @aleksandarmilicevic, sorry for my delay :)

I am a software developer passionate about mobile applications and the .Net platform. In 2014 I won Microsoft’s ImagineCup National Finals and was selected for the world finals with Reverse, the first mobile app that allows to you to travel the past and rediscover the places you already know. Lately I have been focusing on cross platform development, in particular with Xamarin, and at the beginning of 2016 I completed a 6 months internship in Micorsoft’s DX division. Right now I am completing my studies of Computer Engineering at Politecnico di Milano 

I'll rebase, squash and sign the commits :) 
Thanks,
Alessandro

**Comment by pkriens** [comment]
Thanks! Appreciated! I hope we get more of these commits, looking forward to work with you.

**Comment by poz1** [comment]
All right, took me some time as I'm not very familiar with Gradle & the other tools but it should be good now :)

**Comment by pkriens** [comment]
I found a number of issues. It was a bit surprising that the dist jar did not work since it did not include the new core project. It looks like you made the changes without the help of Eclipse/bndtools. This might have gone much faster using Eclipse/bndtools since it gave several warnings that were relevant in this context. (Some of these warnings are also in the gradle output but since Alloy has not been scrubbed of warnings they are often hard to spot.)

Please inspect the changes I made.

**Pull request merged**
