### PR TITLE
Remove the unused EXH and PART tokens

### LINKED ISSUE #110: Remove `exh` and `part` from errors, syntax
From http://alloytools.org/quickguide/a4.html

> We don’t allow “part” and “exh” in declarations any more.

Both can show up in syntax errors

image

### PR DESCRIPTION
**Pull request by pkriens**
Fixes #110

### CODE REVIEW

**Review by grayswandyr — APPROVED** [review]
Looks good to me.

**Comment by pkriens** [comment]
@nmacedo could you take a quick look? Since it touches the parser files I want to be sure ...

**Comment by pkriens** [comment]
@grayswandyr thanks btw :-)

**Comment by nmacedo** [comment]
Looks good, I've just removed additional deprecated code in 36607f6.

**Pull request merged**
