### PR TITLE
Added a run command

### PR DESCRIPTION
**Pull request by pkriens**

### CODE REVIEW

**Comment by grayswandyr** [comment]
Thanks.

* I don't really get how this works. IIUC, I should add `-e` to the commandline? But wouldn't it be more user-friendly if launching this shell could be disconnected from `exec`? I.e add a `shell` directive. And then allow to run an `/exec` command from the shell.
* `/state` is a a `goto state`? 
* what does `/continue` correspond to? `New config`, `New trace`...? 

What we call a _configuration_ is one full valuation of static sigs and fields., up to symmetry. Other `New ...` commands do not change the configuration, just the valuation of _var_ sigs and fields (in a given configuration). So if you click `New ...` repeatedly, you may exhaust all traces _for the current configuration_, but there may be others in other configurations (until you also exhaust all traces in all other configurations).

What would be really useful isn't necessarily linked to the shell: on the command line, even, I'd love to be able to issue a `--all`  option to `exec` to get back all possible instances for a command (in a directory or in a file up to your convenience).

**Comment by grayswandyr** [comment]
To me, the biggest added value of the shell is for people who can't use the GUI for some reason. 

OTOH I think getting all instances for a command, non-interactively, is really useful because this is not something for which you have an alternative, even in the GUI as -there- you must click and click again until exhaustion. This adds to Alloy something that you must usually do at the programmatic level, in Kodkod/Pardinus. As to whether it's better to use a single file or a directory, I think the decision can be made based on what's the simplest for you, once again we don't need too much sophistication (a directory nicely separates instances, but a single file would make it easier to add metadata relative to the whole generation operation, as full time, etc.). What you did here is already great and helpful, so if you think you can allocate a bit more time to development, perhaps it'd be better to address other issues (e.g. we desperately lack a Replace command in the editor #198)

**Comment by pkriens** [comment]
As I said, the shell is in a phase that it is 2 mins to add some functionality. Mucking around in the GUI, especially in Alloy, is always costing 10x the time I estimate :-( But I can take a look.

**Comment by grayswandyr** [comment]
Forget it then. My point was that we already have a great feature with the new CLI and if we can gather all instances for a command with a single command-line option. The rest is icing on the cake.

**Comment by grayswandyr** [comment]
I'm not sure the change comes from this work exactly, but nuXmv isn't listed as a possibility in my build:
```
~/REPOS/org.alloytools.alloy (feature/cli2 ✘)✹✭ ᐅ java -jar org.alloytools.alloy.dist/target/org.alloytools.alloy.dist.jar solvers -l
MiniSat
Lingeling
Glucose
Glucose41
CryptoMiniSat
ZChaffMincost
SAT4J
Electrod/NuSMV
Output CNF to file
Output Kodkod to file
```

**Comment by pkriens** [comment]
Electrod is listed? This branch has no changes in this natives ...

**Comment by grayswandyr** [comment]
```
~/REPOS/org.alloytools.alloy (feature/cli2 ✘)✹✭ ᐅ java -jar org.alloytools.alloy.dist/target/org.alloytools.alloy.dist.jar natives   
┌───────────────────────┬───────────────────┬───────────────────┬──────────────────────┬─────────────────┬───────────┐
│                       │Linux/amd64        │Linux/x86          │MacOS Intel           │Windows/x86      │MacOS Apple│
├───────────────────────┼───────────────────┼───────────────────┼──────────────────────┼─────────────────┼───────────┤
│MiniSat                │libminisat.so      │libminisat.so      │libminisat.dylib      │minisat.dll      │           │
├───────────────────────┼───────────────────┼───────────────────┼──────────────────────┼─────────────────┼───────────┤
│MiniSatX1              │                   │libminisatx1.so    │                      │                 │           │
├───────────────────────┼───────────────────┼───────────────────┼──────────────────────┼─────────────────┼───────────┤
│MiniSat with Unsat Core│libminisatprover.so│libminisatprover.so│libminisatprover.dylib│minisatprover.dll│           │
├───────────────────────┼───────────────────┼───────────────────┼──────────────────────┼─────────────────┼───────────┤
│Lingeling              │liblingeling.so    │liblingeling.so    │liblingeling.dylib    │                 │           │
├───────────────────────┼───────────────────┼───────────────────┼──────────────────────┼─────────────────┼───────────┤
│Glucose                │libglucose.so      │libglucose.so      │libglucose.dylib      │                 │           │
├───────────────────────┼───────────────────┼───────────────────┼──────────────────────┼─────────────────┼───────────┤
│Glucose41              │libglucose41.so    │                   │libglucose41.dylib    │                 │           │
├───────────────────────┼───────────────────┼───────────────────┼──────────────────────┼─────────────────┼───────────┤
│CryptoMiniSat          │libcryptominisat.so│libcryptominisat.so│                      │                 │           │
├───────────────────────┼───────────────────┼───────────────────┼──────────────────────┼─────────────────┼───────────┤
│ZChaffMincost          │libzchaffmincost.so│                   │                      │                 │           │
├───────────────────────┼───────────────────┼───────────────────┼──────────────────────┼─────────────────┼───────────┤
│SAT4J                  │                   │                   │                      │                 │           │
├───────────────────────┼───────────────────┼───────────────────┼──────────────────────┼─────────────────┼───────────┤
│Electrod/NuSMV         │electrod           │                   │electrod              │electrod.exe     │           │
├───────────────────────┼───────────────────┼───────────────────┼──────────────────────┼─────────────────┼───────────┤
│Electrod/nuXmv         │electrod           │                   │electrod              │electrod.exe     │           │
├───────────────────────┼───────────────────┼───────────────────┼──────────────────────┼─────────────────┼───────────┤
│Output CNF to file     │                   │                   │                      │                 │           │
├───────────────────────┼───────────────────┼───────────────────┼──────────────────────┼─────────────────┼───────────┤
│Output Kodkod to file  │                   │                   │                      │                 │           │
└───────────────────────┴───────────────────┴───────────────────┴──────────────────────┴─────────────────┴───────────┘
```

**Comment by grayswandyr** [comment]
That was it, thanks.

**Comment by pkriens** [comment]
@grayswandyr could you approve the request? I want to close this and it is pretty small and I am getting confused with the different PRs outstanding ...

**Comment by grayswandyr** [comment]
What is the preferred policy? Squash and merge or rebase and merge?

**Comment by pkriens** [comment]
Just do a review ok and then I can merge.

**Comment by grayswandyr** [comment]
One last question: it's not clear to me whether you have implemented an option for `exec` to yield all instances (incl. Skolems) for a command? Without going through the evaluator (`-e`).

**Comment by pkriens** [comment]
Do not specify -c will iterate over all commands. The skolems should be in there.

But before we continue, I really need to get a single branch again. It is getting too messy for me so I need it all on master.

**Comment by grayswandyr** [comment]
Not all commands, all instances for one command (e.g. all instances for a `run`, or all counter-examples for a `check`).

**Review by grayswandyr — APPROVED** [review]

**Pull request merged**
