### PR TITLE
ignored files generated by script closes #91

### LINKED ISSUE #91: Files no longer ignored after code refactoring
Hello,
These files (Under **org.alloytools.alloy.core/src/main/java/edu/mit/csail/sdg/parser**):
- CompLexer.java
- CompParser.java
- CompSym.java

Are generated upon build by some scripts in the same directory (as the scripts) and are supposed to be ignored, but the .gitignore(In the root of the repo) is still referencing the old path for the 3 files **(org.alloytools.alloy.application/src/main/java/edu/mit/csail/sdg/alloy4compiler/parser)**.

_It is a minor but annoying matter as whenever you build the generation date in the 3 files are changed._

Regards.

### PR DESCRIPTION
**Pull request by AbderrahmanL**
Hello, 

I moved these lines to a .gitignore under the **org.alloytools.alloy.core**, as i noticed you guys are doing with the other projects, I hope this was helpful more than it's distracting.

Regards.

### CODE REVIEW

**Comment by pkriens** [comment]
This is intended. It is very annoying for eclipse users to have to go to the gradle build and manually build these files.

If you work in Eclipse, you never have to touch gradle.

**Comment by AbderrahmanL** [comment]
I see it's worth it since eclipse is used a lot, i use vscode and command
line for everything, no big deal ill ignore them in my fork there will be
no conflicts ... win-win!

**Comment by pkriens** [comment]
Make sure the .gitignore is not in your PR's.

I understand vs code might have some advantageous features but I see a lot of people that avoid Eclipse missing out on a hell of a lot of features. I work as a consultant and I am always flabbergasted how much more time people spend in Intellij and vs code only to avoid Eclipse. The edit/debug cycle in Eclipse with bndtools is 10x faster than those environments. It might be worth to have a try ...

**Comment by AbderrahmanL** [comment]
And this is what i will do, no better place to take advice, thank you!

**Comment by pkriens** [comment]
But please do not forget that I am rather biased as one of the primary developers of bnd(tools) :-)

**Pull request closed without merging**
