### PR TITLE
Huge update of native code handling

### PR DESCRIPTION
**Pull request by pkriens**
- Added Pardinus source code back into Alloy. Required to cleanup the native code.
- Update to the pardinus core for the SATFactory usage as identifier
- Added native code project
- Update to the native code handling
- Just removed some files to test that were used as examples
- Adaptions to the new native code handling
- Needed for eclipse

### CODE REVIEW

**Comment by grayswandyr** [comment]
Looks like a lot of work indeed. 

> Since this was moved out in 6, I moved it back in. If this works, it can go back to its original.

Is this update is compatible with Pardinus being in its own repo *without further burden on the Pardinus team*? Or does moving Pardinus back to its repo incur some extra work for the team (such as handling a specific build configuration)? In the latter case, the added value for building would objectively result in a loss on the Pardinus side.

**Comment by pkriens** [comment]
I know this is probably felt as insensitive from my side, and I sincerely apologize for this. I hope you can see my site. I wasted days having the repo outside Alloy. The JARs from Alloy did not have the right metadata and there is no github action to build it. The Pardinus repo has not had a commit for 2.5 years so it does not seem very alive? I just got tired of having to pay the price of having these projects as separate repos while nobody seems to have any advantage. 

The changes in the solver code itself were very small. The SATSolver is completely changed but has the same API except for the hardcoded references and the native files have been moved to the native code jar. 

Since the code will get a lot more building love in Alloy, and it

**Comment by grayswandyr** [comment]
I think we're all more than happy that you cleaned up the handling of solvers. But concretely, technically:
- why is it impossible to use a Git submodule? What makes it problematic? Howcome modern tools can't handle a basic decoupling mechanism, by the way I would expect a fierce advocate of good architectural design  likeyou to defend?
- if you only changed SATSolver & NativeCode, isn't it possible to leave the rest of the code in Pardinus?

**Comment by pkriens** [comment]
What is the problem doing the source sync? Then we're completely decoupled? It allows me to apply my build love to the code and it allows the Pardinus people to be 100% independent. 

You have to trust me that the current setup really sucks for me. We can always revisit this in a year if the native code changes are stable.

**Comment by pkriens** [comment]
@grayswandyr @nmacedo we need to come to a conclusion here ... zoom/slack session?

**Comment by grayswandyr** [comment]
Yes, but I think we should ask at least Daniel and Aleks to participate, don't you think?

**Comment by pkriens** [comment]
Agree, you setup a meeting?

**Comment by pkriens** [comment]
For the reviewers ... the build fails because it tries to commit to the master branch the native code. This PR needs to run once on master before that mechanism works. So ignore the native code branch

**Comment by pkriens** [comment]
@nmacedo and @aleksandarmilicevic time to do a review?

**Comment by nmacedo** [comment]
@pkriens still trying to process your impressive work on building the native solvers, but I'm a bit confused about having two `native` folders, one at the root of  `org.alloytools.pardinus.native` (which is included in the resources but contains only a few binaries), and another at `org.alloytools.pardinus.native/satsolvers` that effectively contains all native solvers but doesn't seem to be included in the resources?

**Comment by pkriens** [comment]
I had to look again, at 65 my memory seems to slow down :-(

This should be corrected when I merge on master .. but that is hard to test before I got approval. When I build on native, it will run on a different Github Runner with Macos and build the natives. If this succeeds, I will commit the native directory to master. 

I.e. the idea is to store the native executables in the master branch but I need this PR to work before I can get them on the master branch. It should all work out once this PR is approved. Chicken egg problem :-( Once it works once, it should be straightforward.

**Comment by grayswandyr** [comment]
@pkriens  BTW how is the Electrod binary handled with your work? Is it procured and rebuilt automatically, or does it rely on a pre-compiled binary as before?

**Comment by pkriens** [comment]
I think the binary is handled as an external executable. I recall it was ocaml and they did not support generating arm64 binaries? Wasn't it also quite large?

**Comment by grayswandyr** [comment]
> I think the binary is handled as an external executable.

Will it still be integrated inside the JAR? 



> I recall it was ocaml and they did not support generating arm64 binaries?

It is the best programming language in the world, yes :-) AFAIK it works under arm64.



> Wasn't it also quite large?

Several megas per platform, I guess you may call this large when multiplied by the number of supported platforms.

**Review by aleksandarmilicevic — APPROVED** [review]

**Review by nmacedo — APPROVED** [review]

**Comment by pkriens** [comment]
tomorrow I will work on Alloy ... got myself extremely neck deep in AI and starting to hate it. It is the absolute opposite of formal ... sorry for the delay

**Comment by IftekharUddin** [comment]
i'm trying to implement AlloyMax with alloy6 and this was a big puzzle i needed :) I kept looking on on the documentation site https://alloytools.org/documentation/alloy-api/index.html and looking for the SatSolver Enum only to wonder if i was insane. This explains SO much!

**Pull request merged**
